using System;
using Content.Client.Voice;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Maths;

namespace Content.Client.UserInterface.Systems.Voice.Widgets;

[GenerateTypedNameReferences]
public sealed partial class VoiceHudWidget : UIWidget
{
    private IVoiceChatManager? _voiceManager;

    public VoiceHudWidget()
    {
        RobustXamlLoader.Load(this);
        UpdateState(false, 0f);
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();

        if (_voiceManager == null && IoCManager.Instance?.TryResolveType<IVoiceChatManager>(out var manager) == true)
        {
            _voiceManager = manager;
            _voiceManager.OnLocalSpeaking += OnLocalSpeaking;
        }
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        if (_voiceManager != null)
        {
            _voiceManager.OnLocalSpeaking -= OnLocalSpeaking;
            _voiceManager = null;
        }
    }

    private void OnLocalSpeaking(bool speaking, float level)
    {
        UpdateState(speaking, level);
    }

    public void UpdateState(bool speaking, float level)
    {
        MicIcon.Modulate = speaking ? Color.FromHex("#39FF14") : Color.FromHex("#8A9BA8");
        VolumeBar.Value = Math.Clamp(level * 2.5f, 0f, 1f);
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        if (_voiceManager != null)
        {
            _voiceManager.OnLocalSpeaking -= OnLocalSpeaking;
            _voiceManager = null;
        }
    }
}
